package webapi.command;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;
import net.arnx.jsonic.JSON;
import net.arnx.jsonic.JSONHint;
import com.amazonaws.services.dynamodb.model.*;
import com.amazonaws.services.dynamodb.datamodeling.*;

@DynamoDBTable(tableName="commands")
public class Command extends data.Dynamoo{
	
	//static SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
	static SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd HH:mm (ss.SSS)");
	
	public Command() throws IOException {
		super();
	}
	@JSONHint(ordinal=0) public Who who;
	@JSONHint(ordinal=1) public Date req;
	@JSONHint(ordinal=2) public Date res; 
	@JSONHint(ordinal=3) public Method method;
	@JSONHint(ordinal=4) public String ans;

	@DynamoDBHashKey(attributeName="user_name")
	public String getUid(){return who.uid;}
	public void setUid(){}
	
	
	@DynamoDBAutoGeneratedKey
	
	@DynamoDBRangeKey(attributeName="received_time")
	public String getReceivedTime(){return fmt.format(req);}
	public void setReceivedTime(){}
	
	@DynamoDBAttribute(attributeName="M")
	public String getseeM(){return method.name;}
	
	public void save(){
		/*
		Map<String,AttributeValue> item = new HashMap<String,AttributeValue>();
		JSON json = new JSON();
		json.setDateFormat("yyyy/MM/dd HH:mm(ss.sss)");
		item.put("seq", new AttributeValue().withN("123"));
		item.put("user_name", new AttributeValue().withS(this.who.uid));
		item.put("time", new AttributeValue().withS(fmt.format(new Date())));
		item.put("usertype", new AttributeValue().withS("su"));
		String tableName ="cmd";
		PutItemRequest r = new PutItemRequest(tableName, item);
		client.putItem(r);
		*/
		DynamoDBMapper mapper = new DynamoDBMapper(client);
		mapper.save(this);
	}
	public List userActs(String uid){
		/*
		String n = this.getClass().getName();
		DBCollection coll = db.getCollection(n);
		BasicDBObject query = new BasicDBObject();
		query.put("who.uid", uid);
		DBCursor cur = coll.find(query);
		List<DBObject> ls = new ArrayList<DBObject>();
		JSON json = new JSON();
		json.setDateFormat("yyyy/MM/dd_HH:mm:ss.SSS");
		List cmds = new ArrayList<Command>();
		try{
			while(cur.hasNext()){
				DBObject o = cur.next();
				String s = com.mongodb.util.JSON.serialize(o);
				ls.add(o); // TODO we didnot use ls?
				Command cmd = json.parse(s, Command.class);
				cmd.uniqueName = null;
				cmd.who.key = null;
				cmds.add(cmd);
			}
		}finally{
			cur.close();
		}
		*/
		return null;
	}
	
}