package webapi.command;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;

import net.arnx.jsonic.JSON;
import net.arnx.jsonic.JSONHint;
import com.amazonaws.services.dynamodb.model.*;
import com.amazonaws.services.dynamodb.datamodeling.*;

@DynamoDBTable(tableName="cmds")
public class Command extends data.Dynamoo{
	
	public Command() throws IOException {}
	@JSONHint(ordinal=0) public Who who;
	@JSONHint(ordinal=1) public Date when_receive;
	@JSONHint(ordinal=2) public Date when_answer;
	@JSONHint(ordinal=3) public Method method;

	@DynamoDBHashKey(attributeName="uuid")
	@DynamoDBAutoGeneratedKey
	public String getUuid(){return uuid;}
	public void setUuid(String s){this.uuid=s;}
	private String uuid;
	
	@DynamoDBRangeKey(attributeName="received_time")
	public String getWhenReceive(){return fmt.format(when_receive);}
	public void setWhenReceive(String s) throws ParseException{when_receive=fmt.parse(s);}
	
	@DynamoDBAttribute(attributeName="user_name")
	public String getUid(){return who.uid;}
	public void setUid(String s){
		if(who==null){who = new Who();}
		who.uid=s;
	} 

	@DynamoDBAttribute(attributeName="method_name")
	public String getMethodName(){return method.name;}
	public void setMethodName(String s){
		if(method==null){method = new Method();}
		method.name=s;
	}
	
	@DynamoDBAttribute(attributeName="method_params")
	public String getParams(){
		if(method.params==null){
			return "";
		}else{
			return JSON.encode(method.params);
		}
	}
	public void setParams(String s){method.params = JSON.decode(s, Map.class);}
	
	@DynamoDBAttribute(attributeName="answered_time")
	public String getWhenAnswer(){
		if(when_answer==null){
			return "";
		}
		return fmt.format(when_answer);
	}
	public void setWhenAnswer(String s){
		if(s==null){return;}
		try {
			when_answer = fmt.parse(s);
		} catch (ParseException e) {
			when_answer = null;
		}
	}
	
	public void save(){
		DynamoDBMapper mapper = new DynamoDBMapper(client);
		mapper.save(this);
	}


	public static List<String> loginUsers(){
		List<String> ls = new ArrayList<String>();
		ls.add("John");
		ls.add("Paul");
		ls.add("Richard");
		ls.add("George");
		return ls;
	}
	
	public static List<Command> userActs(String uid){
		DynamoDBScanExpression scan = new DynamoDBScanExpression();
		scan.addFilterCondition("user_name", new Condition()
				.withComparisonOperator(ComparisonOperator.EQ)
				.withAttributeValueList(new AttributeValue().withS("太田直宏")));
		DynamoDBMapper mapper = new DynamoDBMapper(client);
		List<Command> ls = mapper.scan(Command.class, scan);
		if(ls==null){
			try {
				ls.add(new Command());
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return ls;
	}
	
}