package webapi.command;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;

import net.arnx.jsonic.JSON;
import net.arnx.jsonic.JSONHint;
import com.amazonaws.services.dynamodb.model.*;
import com.amazonaws.services.dynamodb.datamodeling.*;

@DynamoDBTable(tableName="cmds")
public class Command extends data.Dynamoo{
	
	//static SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
	static SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd HH:mm (ss.SSS)");
	
	public Command() throws IOException {
		super();
	}
	@JSONHint(ordinal=0) public Who who;
	@JSONHint(ordinal=1) public Date req;
	@JSONHint(ordinal=2) public Date res; 
	@JSONHint(ordinal=3) public Method method;
	@JSONHint(ordinal=4) public String ans;

	
	public String getUid(){return who.uid;}
	public void setUid(){}

	@DynamoDBHashKey(attributeName="uuid")
	@DynamoDBAutoGeneratedKey
	public String getUuid(){return uuid;}
	public void setUuid(String s){this.uuid=s;}
	private String uuid;
	
	@DynamoDBRangeKey(attributeName="received_time")
	public String getReceivedTime(){return fmt.format(req);}
	public void setReceivedTime(){}
	
	@DynamoDBAttribute(attributeName="M")
	public String getseeM(){return method.name;}
	
	public void save(){
		DynamoDBMapper mapper = new DynamoDBMapper(client);
		mapper.save(this);
	}

	public static List loginUsers(){
		List<String> ls = new ArrayList<String>();
		ls.add("John");
		ls.add("Paul");
		ls.add("Richard");
		ls.add("George");
		return ls;
	}
	
	public static List userActs(String uid){
		List<String> ls = new ArrayList<String>();
		ls.add("yay");
		ls.add("hear me ?");
		ls.add("woowww");
		return ls;
		/*
		String n = this.getClass().getName();
		DBCollection coll = db.getCollection(n);
		BasicDBObject query = new BasicDBObject();
		query.put("who.uid", uid);
		DBCursor cur = coll.find(query);
		List<DBObject> ls = new ArrayList<DBObject>();
		JSON json = new JSON();
		json.setDateFormat("yyyy/MM/dd_HH:mm:ss.SSS");
		List cmds = new ArrayList<Command>();
		try{
			while(cur.hasNext()){
				DBObject o = cur.next();
				String s = com.mongodb.util.JSON.serialize(o);
				ls.add(o); // TODO we didnot use ls?
				Command cmd = json.parse(s, Command.class);
				cmd.uniqueName = null;
				cmd.who.key = null;
				cmds.add(cmd);
			}
		}finally{
			cur.close();
		}
		*/
	}
	
}